name: Close old pending proposals

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          daysUntilClose: 30
          responseRequiredLabel: "proposal: changes needed 👷"
          closeComment: >
            This issue has been automatically closed because there has been no response
            to our request to make the necessary changes. You can reopen this issue once more information
            is available.
